defaults:
  - dataset: libero
  - policy_io: libero_no_rgb
  - _self_

dataset:
  dataset:
    data_dir: /XYFS02/HDD_POOL/nju_shklu/nju_shklu_1/Video-as-action-generation-source/mimic-video/data/libero_object_full
